// src/components/fields/InputField.vue
<template>
  <div
    :class="{
      'input-field--error': errorMessage,
      'input-field--disabled': $attrs.disabled
    }"
    class="input-field"
  >
    <FieldLabel :label="label">
      <template #label-right>
        <template v-if="$slots['label-right']">
          <slot name="label-right" />
        </template>
      </template>

      <input
        v-bind="computedAttrs"
        :type="type"
        :value="modelValue"
        :style="inputFieldStyles"
        :tabindex="tabindex"
        :min="minValue"
        class="input-field__input"
        autocomplete="off"
        autocorrect="off"
        autocapitalize="off"
        spellcheck="false"
      >
    </FieldLabel>

    <template v-if="isSubLabelExist">
      <div class="input-fields__sublabel">
        <slot name="subLabel" />
      </div>
    </template>

    <FieldError :error-message="errorMessage" />
  </div>
</template>

<script lang="ts">
import { KEYBOARD_CODES } from 'shared-types';
import { defineComponent, computed } from 'vue';

import FieldLabel from './components/FieldLabel.vue';
import FieldError from './components/FieldError.vue';

export const MODEL_EVENTS = {
  input: 'update:modelValue',
};

export default defineComponent({
  components: {
    FieldLabel,
    FieldError,
  },
  props: {
    label: { type: String, default: undefined },
    modelValue: { type: [String, Number], default: undefined },
    type: { type: String, default: undefined },
    tabindex: { type: String, default: undefined },
    errorMessage: { type: String, default: undefined },
    inputFieldStyles: { type: Object, default: undefined },
    onlyPositive: Boolean,
  },
  setup(props, { attrs, emit, slots }) {
    const computedAttrs = {
      ...attrs,
      onInput: event => {
        if (props.modelValue === event.target.value) return;
        emit(MODEL_EVENTS.input, event.target.value);
      },
      onkeypress: (event: KeyboardEvent) => {
        if (props.type === 'number') {
          if (event.keyCode === KEYBOARD_CODES.keyE) {
            event.preventDefault();
          }
        }
        if (props.onlyPositive) {
          if (
            [
              KEYBOARD_CODES.minus,
              KEYBOARD_CODES.equal,
              KEYBOARD_CODES.plus,
            ].includes(event.keyCode)
          ) {
            event.preventDefault();
          }
        }
      },
    };

    const minValue = computed<number>(() => {
      if (props.onlyPositive && !attrs.min) {
        return 0;
      }
      if (attrs.min < 0) {
        return 0;
      }

      return attrs.min as number;
    });

    const isSubLabelExist = computed(() => !!slots.subLabel);

    return {
      minValue,
      computedAttrs,
      isSubLabelExist,
    };
  },
});
</script>

<style lang="scss">
.input-field {
  position: relative;
  width: 100%;
  flex: 1;
}
.input-field__input {
  font-size: 16px;
  line-height: 1;
  color: var(--app-on-surface-color);
  font-weight: 400;
  letter-spacing: 0.5px;
  padding: 12px 24px;
  background-color: var(--app-surface-color);
  border: 1px solid #acafb3;
  box-sizing: border-box;
  border-radius: var(--system-border-radius);
  outline: none;
  width: 100%;

  @include placeholder-custom(rgba(var(--app-on-surface-color-rgb), 0.6));
}
.input-fields__sublabel {
  position: absolute;
  right: 0;
  top: 0;
  font-size: 16px;
  font-weight: 400;
  color: rgba(var(--app-on-surface-color-rgb), 0.95);

  a {
    color: #ffffff;
    text-decoration: none;
  }
}
</style>

// src/components/fields/input-field/index.tsx
import { KEYBOARD_CODES } from 'shared-types'
import { useMemo } from 'react'
import FieldLabel from '@/components/fields/components/field-label'
import FieldError from '@/components/fields/components/field-error'
import './index.scss'

interface Props extends React.ComponentPropsWithoutRef<'input'> {
  errorMessage?: string,
  label?: string,
  labelRight?: string,
  subLabel?: React.ReactNode,
  onlyPositive?: boolean,
}

export function Component({ errorMessage, label, subLabel, labelRight, disabled, onlyPositive, className, ...props }: Props) {
  const inputProps = {
    ...props,
    onKeyUp: (event: React.KeyboardEvent<HTMLInputElement>) => {
      if (!props.onKeyUp) return

      if (props.type === 'number') {
        if (event.keyCode === KEYBOARD_CODES.keyE) {
          event.preventDefault()
          return
        }
      }
      if (onlyPositive) {
        if (
          [
            KEYBOARD_CODES.minus,
            KEYBOARD_CODES.equal,
            KEYBOARD_CODES.plus,
          ].includes(event.keyCode)
        ) {
          event.preventDefault()
          return
        }
      }

      props.onKeyUp(event)
    },
  }

  const minValue = useMemo(() => {
    if (onlyPositive && !props.min) {
      return 0
    }
    if (Number(props.min) < 0) {
      return 0
    }

    return props.min ? Number(props.min) : null
  }, [props.min, onlyPositive])

  return (
    <div
      className={`
        input-field
        ${errorMessage ? 'input-field--error' : ''}
        ${disabled ? 'input-field--disabled' : ''}
        ${className}
      `}
    >
      <FieldLabel label={label} labelRight={labelRight}>
        <input
          v-bind="computedAttrs"
          {...inputProps}
          min={minValue}
          className="input-field__input"
          autoComplete="off"
          autoCorrect="off"
          autoCapitalize="off"
          spellCheck="false"
        />
      </FieldLabel>

      {subLabel}

      {errorMessage && (
        <FieldError errorMessage={errorMessage} />
      )}
    </div>
  )
}

export default Component
