// src/pages/auth/login/index.tsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ERROR_CODES } from 'shared-types'
import { useAppDispatch } from '@/stores/redux/store'
import { login } from '@/stores/redux/auth'
import FormWrapper from '@/components/fields/components/form-wrapper'
import InputField from '@/components/fields/input-field'
import UiButton from '@/components/common/button'
import './styles.scss'

export function Component() {
  const dispatchRedux = useAppDispatch()
  const routerNavigate = useNavigate()

  const [formData, updateFormData] = useState({
    username: '',
    password: '',
  })

  const [isFormLoading, setFormLoading] = useState(false)
  const [formError, setFormError] = useState('')

  const onChangeInput = (field: keyof typeof formData, value: string | number) => {
    updateFormData({ ...formData, [field]: value })
  }

  const submit = async (event) => {
    event.preventDefault()

    try {
      const { password, username } = formData;

      setFormLoading(true)

      await dispatchRedux(login({ username, password }))

      routerNavigate('/dashboard')
    } catch (e) {
      const errorCodes = {
        [ERROR_CODES.notFound]: 'Incorrect email or password.',
        [ERROR_CODES.invalidCredentials]: 'Password is invalid.',
      };

      setFormError(errorCodes[e.code] || 'Unexpected error.')
    } finally {
      setFormLoading(false);
    }
  };

  return (
    <div className="login">
      <form
        className="login__wrapper"
        onSubmit={submit}
      >
        <h1 className="login__title">
          Log in to account
        </h1>
        <FormWrapper
          error={formError}
          className="login__fields"
        >
          <InputField
            value={formData.username}
            name="username"
            label="Your username"
            placeholder="ie. johnsnow"
            className="login__field"
            disabled={isFormLoading}
            onChange={event => onChangeInput('username', event.target.value)}
          />
          <InputField
            value={formData.password}
            name="password"
            label="Your password"
            className="login__field"
            type="password"
            disabled={isFormLoading}
            onChange={event => onChangeInput('password', event.target.value)}
          />
        </FormWrapper>
        <UiButton
          type="submit"
          className="login__submit"
          disabled={isFormLoading}
        >
          {isFormLoading ? 'Loading...' : 'Log in'}
        </UiButton>
        <div className="login__signup">
          Don’t have an account?

          <Link
            to="sign-up"
            className="login__signup-link"
          >
            Sign up
          </Link>
        </div>
      </form>
    </div>
  )
}

export default Component

// src/pages/auth/Login.vue
<template>
  <div class="login">
    <div
      class="login__wrapper"
      @keypress.enter="submit"
    >
      <h1 class="login__title">
        Log in to account
      </h1>
      <FormWrapper
        :error="formError"
        class="login__fields"
      >
        <InputField
          v-model="form.username"
          name="username"
          label="Your username"
          placeholder="ie. johnsnow"
          class="login__field"
          :disabled="isFormLoading"
          :error-message="getFieldErrorMessage('form.username')"
        />
        <InputField
          v-model="form.password"
          label="Your password"
          class="login__field"
          type="password"
          :disabled="isFormLoading"
          :error-message="getFieldErrorMessage('form.password')"
        />
      </FormWrapper>
      <Button
        class="login__submit"
        :disabled="isFormLoading"
        @click="submit"
      >
        {{ isFormLoading ? 'Loading...' : 'Log in' }}
      </Button>
      <div class="login__signup">
        Don’t have an account?

        <router-link
          to="sign-up"
          class="login__signup-link"
        >
          Sign up
        </router-link>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { ERROR_CODES } from 'shared-types';
import {
  defineComponent, ref, Ref, watch,
} from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '@/stores';
import { useFormValidation } from '@/composable';
import { required, minLength } from '@/js/helpers/validators.helper';

import FormWrapper from '@/components/fields/FormWrapper.vue';
import Button from '@/components/common/Button.vue';
import InputField from '@/components/fields/InputField.vue';

export default defineComponent({
  components: {
    Button,
    InputField,
    FormWrapper,
  },
  setup() {
    const router = useRouter();
    const { login } = useAuthStore();

    const form = ref({
      username: '',
      password: '',
    });
    const isFormLoading = ref(false);
    const formError: Ref<string | null> = ref(null);

    const {
      isFormValid,
      getFieldErrorMessage,
    } = useFormValidation(
      { form },
      {
        form: {
          username: { required },
          password: {
            required,
            passwordMinLength: minLength(6),
          },
        },
      },
      undefined,
      {
        customValidationMessages: {
          passwordMinLength: 'Minimal length is 6.',
        },
      },
    );

    watch(form.value, () => { formError.value = null; });

    const submit = async () => {
      if (!isFormValid()) return;

      const { password, username } = form.value;

      try {
        isFormLoading.value = true;

        await login({ password, username });

        router.push({ name: 'dashboard' });
      } catch (e) {
        const errorCodes = {
          [ERROR_CODES.notFound]: 'Incorrect email or password.',
          [ERROR_CODES.invalidCredentials]: 'Password is invalid.',
        };

        formError.value = errorCodes[e.code] || 'Unexpected error.';
      } finally {
        isFormLoading.value = false;
      }
    };

    return {
      form,
      formError,
      isFormLoading,
      submit,
      getFieldErrorMessage,
    };
  },
});
</script>

<style lang="scss" scoped>
.login {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--app-bg-color);
}
.login__wrapper {
  width: 100%;
  max-width: 450px;
  padding: 48px 32px;
}
.login__title {
  font-weight: 500;
  font-size: 30px;
  line-height: 1.4;
  text-align: center;
  margin-bottom: 40px;
  color: var(--app-on-bg-color);
}
.login__field {
  &:not(:last-child) {
    margin-bottom: 24px;
  }
}
.login__submit {
  margin: 32px auto 0;
}
.login__signup {
  margin-top: 40px;
  text-align: center;
  font-weight: 400;
  color: var(--app-on-bg-color);
}
.login__signup-link {
  transition: .2s ease-out;
  color: var(--primary-500);

  &:hover {
    color: var(--primary-700);
  }
}
</style>
