// src/components/fields/form-wrapper.vue
<template>
  <div class="form-wrapper">
    <template v-if="Array.isArray(error)">
      <div class="form-wrapper__error-list">
        <template
          v-for="item in error"
          :key="item"
        >
          <p class="form-wrapper__error">
            {{ item }}
          </p>
        </template>
      </div>
    </template>
    <template v-else>
      <div class="form-wrapper__error-list">
        <p class="form-wrapper__error">
          {{ error }}
        </p>
      </div>
    </template>

    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  props: {
    error: { type: [Array, String], default: undefined },
  },
});
</script>

<style lang="scss" scoped>
.form-wrapper__error-list {
  display: grid;
  grid-gap: 8px;

  margin-bottom: 16px;
}
.form-wrapper__error {
  text-align: center;
  color: var(--app-danger-color-text);
  font-size: 14px;
  line-height: 1.3;
}
</style>

// src/components/fields/components/form-wrapper/index.tsx
import './index.scss'

interface Props extends React.ComponentPropsWithoutRef<'div'> {
  error?: string | string[],
  children?: React.ReactNode,
}

export function Component({ error, children, ...props }: Props) {
  const ErrorRenderer = () => {
    if (Array.isArray(error)) {
      return error.map(item => (
        <p className="form-wrapper__error" key={item}>
          {item}
        </p>
      ))
    }

    return (
      <p className="form-wrapper__error">
        {error}
      </p>
    )
  }

  return (
    <div className="form-wrapper" {...props}>
      <div className="form-wrapper__error-list">
        <ErrorRenderer />
      </div>

      {children}
    </div>
  )
}

export default Component
